name: Perform Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Update version
        run: |
          # Helm version
          yq e -i '.version = "${{ github.event.inputs.tag }}"' helm/cloudflare-zero-trust-operator/Chart.yaml
          yq e -i '.appVersion = "${{ github.event.inputs.tag }}"' helm/cloudflare-zero-trust-operator/Chart.yaml
          yq e -i '.images[0].newTag = "${{ github.event.inputs.tag }}"' config/manager/kustomization.yaml

          # Version in README.md
          sed -i.bak -e '/<!-- Version_Placeholder -->/ {' -e 'n; s|.*|![Version: ${{ github.event.inputs.tag }}](https://img.shields.io/badge/Version-${{ github.event.inputs.tag }}-informational?style=flat-square)|' -e '}' README.md && rm README.md.bak
          
          # Build Manifests
          make manifests
          # Build Helm chart
          make helm
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          commit: '--allow-empty'
          push: true
          tag: ${{ github.event.inputs.tag }}
          message: Build Release ${{ github.event.inputs.tag }}
